app/models/subscription.py
import braintree
from paypalrestsdk import BillingAgreement

from app import db
from app.utils.sqlalchemy_util import ResourceMixin

class Subscription(ResourceMixin, db.Model):
    __tablename__ = 'subscriptions'
    id = db.Column(db.Integer, primary_key=True)

    # Relationships
    user_id = db.Column(db.Integer, db.ForeignKey('users.id',
                                                  onupdate='CASCADE',
                                                  ondelete='CASCADE'),
                        index=True, nullable=False)

    payment_gateway = db.Column(db.String(128))

    plan_id = db.Column(db.String(128), db.ForeignKey('strategies.plan_id'))
    strategy = db.relationship('Strategy', lazy=True)

    # AKA Agreement Id for PayPal Gateways
    # TODO: Rename to gateway_subscription_id ?
    subscription_id = db.Column(db.String(128))

    active = db.Column(db.Boolean())

    def create(self, user=None, plan_id=None, subscription_id=None,
               payment_gateway=None):
	self.payment_gateway = payment_gateway
	self.user_id = user.id
	self.plan_id = plan_id
	self.subscription_id = subscription_id
	self.active = True

        db.session.add(self)
        db.session.commit()

	return True

    def create_braintree():
        """
        Create a recurring subscription.
        :param user: User to apply the subscription to
        :type user: User instance
        :param name: User's billing name
        :type name: str
        :param plan: Plan identifier
        :type plan: str
        :param coupon: Coupon code to apply
        :type coupon: str
        :param token: Token returned by javascript
        :type token: str
        :return: bool
        """

        #TODO: plan_id and user_id should be unique, I should be updating 
        # old plans if they get reactivated. Implement logic to check this in future.
        # otherwise you can end up with a bunch of unactive plans when you get the user.
        # Which may cause slowness for that user.

        # Set the subscription details.
        self.user_id = user.id
        self.plan_id = plan_id

        # Create the user account if none exists.
        if user.customer_id is None:
            result = braintree.Customer.create()
            if result.is_success:
                user.customer_id = result.customer.id
            else:
                return result

        # Create the payment method
        result = braintree.PaymentMethod.create({
            'customer_id': user.customer_id,
            'payment_method_nonce': payment_method_nonce,
            'options': {
                'verify_card': True
            }
        })

        if result.is_success:
            self.payment_method_token = result.payment_method.token
        else:
            return result

        # Create subscription
        result = braintree.Subscription.create({
            'payment_method_token': self.payment_method_token,
            'plan_id': plan_id
        })

        if result.is_success:
            self.subscription_id = result.subscription.id
            self.active = True
        else:
            return result

        # Commit to database
        db.session.add(user)
        db.session.add(self)

        db.session.commit()

        return result

    def create_stripe():
        pass

    def create_paypal():
        pass
        

    def is_active(self):
        """ DEPERECIATED FUNCTION PLEASE USE active field of subscription"""
        return self.active

    def cancel(self):
    	if self.payment_gateway == 'paypal':
	    return self.cancel_paypal()

    def cancel_paypal(self):
	billing_agreement = BillingAgreement.find(self.subscription_id)    	
        cancel_note = {"note": "Canceled subscription."}
	if billing_agreement.cancel(cancel_note):
	    return True
	else:
	    return False
    	
    def cancel_braintree(self):
        result = braintree.Subscription.cancel(self.subscription_id)
        return result

app/models/user.py
from collections import OrderedDict

from sqlalchemy.ext.hybrid import hybrid_property
from flask_login import UserMixin

from app import bcrypt, db
from app.models.subscription import Subscription
from app.utils.sqlalchemy_util import ResourceMixin

class User(UserMixin, ResourceMixin, db.Model):
    ROLE = OrderedDict([
        ('guest', 'Guest'),
        ('member', 'Member'),
        ('admin', 'Admin')
    ])

    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True, nullable=False)
    _password = db.Column('password', db.String(128))
    role = db.Column(db.Enum(*ROLE, name='role_types'),
                     nullable=False, server_default='member')

    # Relationships
    subscriptions = db.relationship(Subscription, backref='users', passive_deletes=True)

    # Billing
    customer_id = db.Column(db.String(128))


    @hybrid_property
    def password(self):
        return self._password

    @password.setter
    def _set_password(self, plaintext):
        self._password = bcrypt.generate_password_hash(plaintext)

    def is_correct_password(self, plaintext):
        return bcrypt.check_password_hash(self._password, plaintext)

    def is_subscribed(self, plan_id):
        plans = filter(lambda subscription: subscription.plan_id == plan_id,
                      self.subscriptions)
        subscribed = len(plans) and plans[0].is_active()

        return subscribed

    #TODO: Should be renamed to cancel_plan or cancel_subscription
    def cancel(self, plan_id):
        plans = filter(lambda subscription: subscription.plan_id == plan_id,
                      self.subscriptions)
        subscribed = len(plans) and plans[0].is_active()

        if subscribed: 
            return plans[0].cancel()
        else:
            return False

app/forms/user.py
from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, Email, Length
from wtforms.validators import ValidationError
from flask_login import current_user

from app.models.user import User, db
from app.utils.validators import Unique

class LoginForm(Form):
    email = TextField('Email', [Length(0, 64)])
    password = PasswordField('Password', [Length(0, 128)])

class UpdateAccountForm(Form):
    email = TextField('Email', [DataRequired(message="Email address required"),
                                Email(message="Not a valid email address"),
                                Length(max=128, message="The email address must be under 128 \
                                                        characters")])
    new_password = PasswordField('Password', [Length(0, 128)])
    current_password = PasswordField('Password', [Length(0, 128)])

    def validate_email(form, field):
        check = User.email.class_.query.filter(User.email == field.data).first()
        if check and current_user.email != field.data:
            raise ValidationError("That email is already in use.")

class SignupForm(Form):
    email = TextField('Email', [DataRequired(message="Email address required"),
                                Email(message="Not a valid email address"),
                                Length(max=128, message="The email address must be under 128 \
                                                        characters"),
                                Unique(User.email, message="That email is already in use")])
                                 
    password = PasswordField('Password', [DataRequired(message="Password field required"),
                                          Length(max=128, message="Password must be under 128 \
                                                                  characters")])

class EmailForm(Form):
    email = TextField('Email')

class PasswordForm(Form):
    password = PasswordField('Password', [DataRequired(message="Password field required"),
                                          Length(max=128, message="Password must be under 128 \
                                                                  characters")])

class EmptyForm(Form):
    pass

app/views/strategy.py
# from app.models.strategy import Strategy

from flask import Blueprint, render_template
from flask_login import current_user

strategy = Blueprint('strategy', __name__)

# @strategy.route('/strategies')
# def strategies():
    # strats = Strategy.query.all()
    # return render_template('strategy/strategies.html', strats=strats)

@strategy.route('/strategy/<strategy_name>')
def strategy_details(strategy_name):
    # TODO This might be an inefficent query, can probably make it faster?
    # Maybe we cache the query in strategies function
    strategy_name = strategy_name.replace('-', ' ')
    # inEfficent query?
    strat = Strategy.query.filter(Strategy.name.ilike(strategy_name)).first()

    # TODO: Add a method to the user class that easily checks if 
    # a user is subscribed to a particular startegy, can save a lot of code :)

    # Check if current user is subscribed to strategy
    if current_user.is_authenticated():
        subscribed = current_user.is_subscribed(strat.plan_id)
    else:
        subscribed = False
        
    return render_template('strategy/details.html', strat=strat, subscribed=subscribed)

app/views/user.py
from flask import (
    abort,
    Blueprint,
    flash,
    url_for,
    redirect,
    request,
    render_template)
from flask_login import current_user, login_user, login_required, logout_user
from app import app
from app import mail
from app.models.user import User
from app.forms.user import LoginForm, SignupForm, EmailForm, PasswordForm, UpdateAccountForm, EmptyForm
from app.utils.security import ts
from app.utils.constants import STANDARD_PLAN_ID
from flask_mail import Message
import requests

user = Blueprint('user', __name__)

@user.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('user.subscription'))

    form = LoginForm()

    if form.validate_on_submit():
        u = User.query.filter_by(email=form.email.data.lower()).first()

        if u and u.is_correct_password(form.password.data):
            login_user(u)
            return redirect(url_for('user.subscription'))
        else:
            flash('Invalid email or password', 'error')

    return render_template('user/login.html', form=form)

@user.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        u = User()

        form.populate_obj(u)
        u.email = form.email.data.lower()
        u.password = form.password.data

        u.save()

        if login_user(u):
            return redirect(url_for('user.subscription'))
    elif len(form.errors):
        flash(form.errors.values()[0][0], 'error')

    return render_template('user/signup.html', form=form)

@user.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('page.home'))

@user.route('/subscription')
@login_required
def subscription():
    if current_user.is_subscribed(STANDARD_PLAN_ID) or current_user.role == 'admin':
        return render_template('user/subscription.html')
    else:
        return redirect(url_for('billing.subscribe'))

# @user.route('/subscriptions')
# @login_required
# def subscriptions():
    # return render_template('user/subscriptions.html', subscriptions=current_user.subscriptions)

@user.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    form = EmailForm()

    if form.validate_on_submit():
        u = User.query.filter_by(email=form.email.data).first()
        if u:
            flash('A password reset email has been sent.')
            subject = 'Password reset requested'
            token = ts.dumps(u.email, salt='recover-key')
            reset_url = url_for('user.password_reset', token=token, _external=True)
            # TODO: Change email/recover to something else like email/reset_password
	    html = render_template('email/recover.html', reset_url=reset_url)
            # SMTP
            # msg = Message(subject, [u.email], html=html, sender=("EquityBuilder", "no-reply@equitybuilder.io"))
            # mail.send(msg)
            # API
	    requests.post(app.config.get('MAILGUN_API_BASE_URL'),
		auth=("api", app.config.get('MAILGUN_API_KEY')),
		data={"from": "EquityBuilder <no-reply@equitybuilder.io>",
		      "to": [u.email],
		      "subject": "Password Reset Requested",
		      "html": html})
        else:
            flash('No user under that email exists.')

    return render_template('user/forgot_password.html', form=form)

@user.route('/password_reset/<token>', methods=['GET', 'POST'])
def password_reset(token):
    try:
        email = ts.loads(token, salt="recover-key", max_age=86400)
    except:
        abort(404)

    form = PasswordForm()
    if form.validate_on_submit():
        u = User.query.filter_by(email=email).first_or_404()
        u.password = form.password.data
        u.save()

        return redirect(url_for('user.login'))
    elif len(form.errors):
            flash(form.errors.values()[0][0], 'error')

    return render_template('user/password_reset.html', form=form, token=token)

@user.route('/settings/account', methods=['GET', 'POST'])
@login_required
def account_settings():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if current_user.is_correct_password(form.current_password.data):
            current_user.email = form.email.data
            if len(form.new_password.data):
                current_user.password = form.new_password.data
            current_user.save()
            flash("Account settings updated.")
        else:
            flash("Incorrect password.", 'error')
    elif len(form.errors):
        flash(form.errors.values()[0][0], 'error')

    return render_template('user/settings.html', form=form, settings='account')

@user.route('/settings/subscription', methods=['GET', 'POST'])
@login_required
def subscription_settings():
    form = EmptyForm()
    if form.validate_on_submit():
        #TODO: Put this plan in a constant somewhere.
        if current_user.cancel(STANDARD_PLAN_ID):
            flash("Your subscription has been canceled.")
        else:
            flash("You currently don't have a subscription.")

    elif len(form.errors):
        flash(form.errors.values()[0][0], 'error')

    return render_template('user/settings.html', form=form, settings='subscription')

app/templates/user/forgot_password.html
{% extends "base.html" %}

{% block title %}Reset Password{% endblock %}

{% block body %}
  <div id="forgot-password">
    <form action="{{ url_for('user.forgot_password') }}" method="post">
      <h1>Reset Password</h1>
      {{ form.email(placeholder='Email Address') }}
      {{ form.hidden_tag() }}
      <button type="submit" class="btn">Reset my password</button>
    </form>
  </div>
{% endblock %}

app/templates/user/login.html
{% extends "base.html" %}

{% block title %}Log In{% endblock %}

{% block body %}
  <div id="login">
    <form action="{{ url_for('user.login') }}" method="post">
      <h1>Log In to EquityBuilder</h1>
      {{ form.email(placeholder='Email Address') }}
      {{ form.password(placeholder='Password') }}
      {{ form.hidden_tag() }}
      <button type="submit" class="btn">Log In</button>
      <div><a href="{{ url_for('user.forgot_password') }}">Forgot Password?</a></div>
    </form>
    <div>Don't have an account? <a href="{{ url_for('user.signup') }}">Sign Up</a></div>
  </div>
{% endblock %}

app/templates/user/password_reset.html
{% extends "layout.html" %}

{% block title %}Reset Password{% endblock %}

{% block body %}
  <div id="password-reset">
    <form action="{{ url_for('user.password_reset', token=token) }}" method="post">
      <h1>Reset Password</h1>
      {% if form.errors %}
        <ul class="field-error">
          {% for error in form.errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      {% endif %}

      {{ form.password(placeholder='Password') }}
      {{ form.hidden_tag() }}
      <button type="submit" class="btn">Update my password</button>
    </form>
  </div>
{% endblock %}

app/templates/user/settings.html
{% extends "layout.html" %}

{% block stylesheet %}
  {{ super() }}
{% endblock %}

{% block title %}Settings{% endblock %}

{% block body %}
  {{ super() }}
  <div class="content" id="settings">
    <div class="sidebar">
      <h1>Settings</h1>
      {% if settings == 'account' %}
        <div><a class="blue label" href="{{ url_for('user.account_settings') }}">Account</a></div>
        <div><a class="label" href="{{ url_for('user.subscription_settings') }}">Subscription</a></div>
      {% else %}
        <div><a class="label" href="{{ url_for('user.account_settings') }}">Account</a></div>
        <div><a class="blue label" href="{{ url_for('user.subscription_settings') }}">Subscription</a></div>
      {% endif %}
    </div>
    <div class="line"></div>
    {% if settings == 'account' %}
      <form class="account-container" action="{{ url_for('user.account_settings') }}" method="post">
        <h1>Edit your account Information</h1>
        <div class="email">Email:</div>
        {{ form.email(value=current_user.email) }}
        <div class="new-password">New Password (only if you want to change your password):</div>
        {{ form.new_password() }}
        <div class="current-password">Current Password (required to make changes):</div>
        {{ form.current_password() }}
        {{ form.hidden_tag() }}
        <button class="btn">Update Account</button>
      </form>
    {% else %}
      <form class="subscription-container" action="{{ url_for('user.subscription_settings') }}" method="post">
        <h1>Cancel your subscription?</h1>
        {{ form.hidden_tag() }}
        <button onclick="return confirm('Are you sure you want to cancel?')" class="btn">Cancel</button>
      </form>
    {% endif %}
  </div>
{% endblock %}

app/templates/user/signup.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block body %}
  <div id="signup">
    <form action="{{ url_for('user.signup') }}" method="post">
      <h1>Sign Up for EquityBuilder</h1>
      {{ form.email(placeholder='Email Address') }}
      {{ form.password(placeholder='Password') }}
      {{ form.hidden_tag() }}
      <button type="submit" class="btn">Get Started</button>
    </form>
    <div>Already have an account? <a href="{{ url_for('user.login') }}">Log In</a></div>
  </div>
{% endblock %}

app/templates/user/subscription.html
{% extends "layout.html" %}

{% block stylesheet %}
  {{ super() }}
{% endblock %}

{% block title %}EquityBuilder{% endblock %}

{% block body %}
  {{ super() }}
  <div class="content" id="holdings">
    <h1>April 2016 Holdings</h1>
    <div class="column">
      <div class="left">
        <h2>Ticker</h2>
        <div class="row">TLT - iShares 20+ Year Treasury Bond</div>
        <div class="row">IEF - iShares 7-10 Year Treasury Bond</div>
        <div class="row">XLY - Consumer Discretionary Select Sector SPDR</div>
        <div class="row">XLV - Health Care Select Sector SPDR</div>
        <div class="row">XLF - Financial Select Sector SPDR</div>
        <div class="row">XLE - Energy Select Sector SPDR</div>
      </div>
      <div class="right">
        <h2>Allocation</h2>
        <div class="row">16.6 %</div>
        <div class="row">16.6 %</div>
        <div class="row">16.6 %</div>
        <div class="row">16.6 %</div>
        <div class="row">16.6 %</div>
        <div class="row">16.6 %</div>
      </div>
    </div>
    <div class="tips">
      <div>* Tip 1: If a stock you hold from the previous month does not appear
        on this list sell it. </div>
      <div>* Tip 2: To maximize profit, sell and buy on the first trading
        day of every month.</div>
    </div>
  </div>
{% endblock %}

app/templates/user/subscriptions.html
{% extends "layout.html" %}

{% block stylesheet %}
  {{ super() }}
{% endblock %}

{% block title %}Subscriptions{% endblock %}

{% block body %}
  {{ super() }}
  <div id="subscriptions">
    <h1>My Subscriptions</h1>
    {% if subscriptions|length == 0 %}
      <div class="item">You have no subscriptions <a href="{{ url_for('strategy.strategies') }}">click here</a> to view strategies.</div>
    {% else %}
      {% for subscription in subscriptions %}
        {% if subscription.is_active() %}
          <a class="item" href="{{ url_for('strategy.strategy_details',
                                   strategy_name=subscription.plan_id) }}">{{ subscription.strategy.name }}</div>
        {% endif %}
      {% endfor %}
    {% endif %}
  </div>
{% endblock %}