app/views/page.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user

page = Blueprint('page', __name__)

@page.route('/')
def home():
    if current_user.is_authenticated:
        return redirect(url_for('user.subscription'))
    return render_template('home.html')

@page.route('/about')
def about():
    return render_template('about.html')

@page.route('/about-the-strategy')
def about_the_strategy():
    return render_template('strategy/about_the_strategy.html')

@page.route('/faq')
def faq():
    return render_template('faq.html')

# @page.route('/blog')
# def blog():
    # return render_template('blog.html')

app/views/user.py
from flask import (
    abort,
    Blueprint,
    flash,
    url_for,
    redirect,
    request,
    render_template)
from flask_login import current_user, login_user, login_required, logout_user
from app import app
from app import mail
from app.models.user import User
from app.forms.user import LoginForm, SignupForm, EmailForm, PasswordForm, UpdateAccountForm, EmptyForm
from app.utils.security import ts
from app.utils.constants import STANDARD_PLAN_ID
from flask_mail import Message
import requests

user = Blueprint('user', __name__)

@user.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('user.subscription'))

    form = LoginForm()

    if form.validate_on_submit():
        u = User.query.filter_by(email=form.email.data.lower()).first()

        if u and u.is_correct_password(form.password.data):
            login_user(u)
            return redirect(url_for('user.subscription'))
        else:
            flash('Invalid email or password', 'error')

    return render_template('user/login.html', form=form)

@user.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        u = User()

        form.populate_obj(u)
        u.email = form.email.data.lower()
        u.password = form.password.data

        u.save()

        if login_user(u):
            return redirect(url_for('user.subscription'))
    elif len(form.errors):
        flash(form.errors.values()[0][0], 'error')

    return render_template('user/signup.html', form=form)

@user.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('page.home'))

@user.route('/subscription')
@login_required
def subscription():
    if current_user.is_subscribed(STANDARD_PLAN_ID) or current_user.role == 'admin':
        return render_template('user/subscription.html')
    else:
        return redirect(url_for('billing.subscribe'))

# @user.route('/subscriptions')
# @login_required
# def subscriptions():
    # return render_template('user/subscriptions.html', subscriptions=current_user.subscriptions)

@user.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    form = EmailForm()

    if form.validate_on_submit():
        u = User.query.filter_by(email=form.email.data).first()
        if u:
            flash('A password reset email has been sent.')
            subject = 'Password reset requested'
            token = ts.dumps(u.email, salt='recover-key')
            reset_url = url_for('user.password_reset', token=token, _external=True)
            # TODO: Change email/recover to something else like email/reset_password
	    html = render_template('email/recover.html', reset_url=reset_url)
            # SMTP
            # msg = Message(subject, [u.email], html=html, sender=("EquityBuilder", "no-reply@equitybuilder.io"))
            # mail.send(msg)
            # API
	    requests.post(app.config.get('MAILGUN_API_BASE_URL'),
		auth=("api", app.config.get('MAILGUN_API_KEY')),
		data={"from": "EquityBuilder <no-reply@equitybuilder.io>",
		      "to": [u.email],
		      "subject": "Password Reset Requested",
		      "html": html})
        else:
            flash('No user under that email exists.')

    return render_template('user/forgot_password.html', form=form)

@user.route('/password_reset/<token>', methods=['GET', 'POST'])
def password_reset(token):
    try:
        email = ts.loads(token, salt="recover-key", max_age=86400)
    except:
        abort(404)

    form = PasswordForm()
    if form.validate_on_submit():
        u = User.query.filter_by(email=email).first_or_404()
        u.password = form.password.data
        u.save()

        return redirect(url_for('user.login'))
    elif len(form.errors):
            flash(form.errors.values()[0][0], 'error')

    return render_template('user/password_reset.html', form=form, token=token)

@user.route('/settings/account', methods=['GET', 'POST'])
@login_required
def account_settings():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if current_user.is_correct_password(form.current_password.data):
            current_user.email = form.email.data
            if len(form.new_password.data):
                current_user.password = form.new_password.data
            current_user.save()
            flash("Account settings updated.")
        else:
            flash("Incorrect password.", 'error')
    elif len(form.errors):
        flash(form.errors.values()[0][0], 'error')

    return render_template('user/settings.html', form=form, settings='account')

@user.route('/settings/subscription', methods=['GET', 'POST'])
@login_required
def subscription_settings():
    form = EmptyForm()
    if form.validate_on_submit():
        #TODO: Put this plan in a constant somewhere.
        if current_user.cancel(STANDARD_PLAN_ID):
            flash("Your subscription has been canceled.")
        else:
            flash("You currently don't have a subscription.")

    elif len(form.errors):
        flash(form.errors.values()[0][0], 'error')

    return render_template('user/settings.html', form=form, settings='subscription')

app/templates/about.html
{% extends "layout.html" %}

{% block stylesheet %}
  {{ super() }}
{% endblock %}

{% block title %}About Us{% endblock %}

{% block body %}
  {{ super() }}
  <div class="content" id="about">
    <h1>About Us</h1>
    <p>EquityBuilder was founded to help the average investor invest smarter. Out preforming the market 
requires a serious time effort of researching stocks, placing trades, and battling emotions. Most Americans
don't even invest because of the immense effort required. EquityBuilder knows how important investing
is to growing your wealth, so we have created a simple low cost strategy that anyone can follow.</p>
  </div>
{% endblock %}

app/templates/base.html
{% import 'macros/flash.html' as flash %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <! -- jquery -->
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>-->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="icon" href="/static/img/favicon.png">

    <!-- Optional theme -->

    <!-- Latest compiled and minified JavaScript -->
		<script>
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

			ga('create', 'UA-75855907-1', 'auto');
			ga('send', 'pageview');
		</script>

    {% block stylesheet %}
      <link rel="stylesheet" type="text/css" href="/static/public/css/app.css">
    {% endblock %}

    {% block script %}
    {% endblock %}

    <title>{% block title %}{% endblock %}</title>
  </head>

  <body>
    {% block header %}{% endblock %}

    <div class="flash">
      {{ flash.render() }}
    </div>

    {% block body %}
    {% endblock %}

    {% block footer %}{% endblock %}
  </body>
</html>

app/templates/blog.html
{% extends "layout.html" %}

{% block stylesheet %}
  {{ super() }}
{% endblock %}

{% block title %}FAQ{% endblock %}

{% block body %}
  {{ super() }}
  <div class="content" id="blog">
    <div>Coming soon</div>
  </div>
{% endblock %}

app/templates/faq.html
{% extends "layout.html" %}

{% block stylesheet %}
  {{ super() }}
{% endblock %}

{% block title %}FAQ{% endblock %}

{% block body %}
  {{ super() }}
  <div class="content" id="faq">
    <h1>Frequently Asked Questions</h1>
    <div class="question">Why am I not receiving any emails?</div>
    <div class="answer">Please check your spam folder. If you're still not receiving them
      make sure you put down the correct email address. You can check your current email by clicking on the settings link
      at the top of the page after you log in. If you are still having problems email us at support@equitybuilder.io, in the
      mean time you can check the current month holdings by logging in.</div>
    <div class="question">When will I receive the stock picks?</div>
    <div class="answer">You will receive the stock picks at the end of the month.</div>
    <div class="question">When should I buy these stocks?</div>
    <div class="answer">To maximize your profit, you should buy the stocks on the first trading day of every month.</div>
    <div class="question">Does it matter when I subscribe?</div>
    <div class="answer">No, it does not.</div>
    <div class="question">How do I cancel my subscription?</div>
    <div class="answer">Log in, click on the settings link at the top of the page, click on subscription on the sidebar,
      then click on the red cancel button. Or click <a href="{{ url_for('user.subscription_settings') }}">here</a>. You
      can also cancel through PayPal.
    </div>
    <div class="question">Have more questions?</div>
    <div class="answer">Contact us at support@equitybuilder.io</div>
  </div>
{% endblock %}

app/templates/home.html
{% extends "layout.html" %}

{% block stylesheet %}
  {{ super() }}
{% endblock %}

{% block title %}EquityBuilder{% endblock %}

{% block body %}
  {{ super() }}

  <div id="investing-made-simple">
    <div class="content container">
      <div class="left">
        <h1>Investing Made Easier.</h1>
        <h2>EquityBuilder creates advanced investing strategies that are safe and outperform 
          <br>the market.</h2>
        <h2>Beat the market for only <strong>$10 / month.</strong></h2>
        <a href="{{ url_for('user.signup') }}" class="btn">Get Started  <i class="fa fa-arrow-right"></i></a>
      </div>
      <div class="right">
        <img src="/static/img/chart.png" alt="chart">
      </div>
    </div>
  </div>
  <hr>
  <div id="the-strategy">
    <div>
      <div class="content container">
        <h1>The Investment Strategy</h1>
        <div class="stats">
          <div class="annual-return">
            <div class="stat">11 %</div>
            <div class="stat-label">Annual Return</div>
            <div class="stat-description">Over the last 10 years the strategy on
              average has returned 11 % every year. This is the return you can
              expect from us. The average investor only returns 7 % per year.</div>
          </div>
          <div class="max-loss">
            <div class="stat">14 %</div>
            <div class="stat-label">Max Loss</div>
            <div class="stat-description">This is the max amount our strategy has ever lost,
              even through 2008, one of the worst financial crisis in US history. 
              To put this into perspective the average investor lost 55 % of there portfolio
              in 2008.</div>
          </div>
          <div class="total-return">
            <div class="stat">220 %</div>
            <div class="stat-label">Total Return</div>
            <div class="stat-description">Over the last 11 years the strategy has returned
              a total of 220 % that means you would have tripled your net worth.
              The average investor returned only 100 % during this time period.</div>
          </div>
        </div>
        <a href="{{ url_for('page.about_the_strategy') }}" class="btn">Learn more <i class="fa fa-arrow-right"></i></a>
      </div>
    </div>
  </div>
  <hr>
  <div id="how-it-works">
    <div class="content container">
      <h1>How it works</h1>
      <div class="steps">
        <div class="left">
          <i class="fa fa-credit-card"></i>
          <h2>Step 1: Subscribe</h2>
          <p>Simply subscribe to our strategy for only $10 a month.
          All major credit cards and PayPal accepted.</p>
        </div>
        <div class="right">
          <i class="fa fa-money"></i>
          <h2>Step 2: Buy the stocks</h2>
          <p>Every month you will get an email that will tell you
          what stocks to buy and how much of your portfolio to allocate
          to each stock.</p>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <div id="why-us">
    <div class="content container">
      <h1>Why Us?</h1>
      <ul>
        <li>We provide a hedge fund level strategy but without the cost and requirements of an actually hedge fund.</li>
        <li>Our strategy is rigorously back tested to ensure it actually works.</li>
        <li>Using an automated strategy keeps your emotions out of the
        market. Just follow the strategy and you will win. We have hundreds of investors already using our strategy.</li>
      </ul>
      <a href="{{ url_for('user.signup') }}" class="btn">Subscribe Now<i class="fa fa-arrow-right"></i></a>
    </div>
  </div>
{% endblock %}

app/templates/index.html
{% extends "layout.html" %}
{% block stylesheet %}
  {{ super() }}
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/index.css') }}">
{% endblock %}
{% block title %}starjar{% endblock %}
{% block body %}
  {{ super() }}
  <div class="ui vertical masthead center aligned segment">
    <div class="ui text container">
    <h1 class="ui header">
      Investing made simple.
    </h1>
    <h2>Starjar creates advanced investing strategies that out perform the market.</h2>
    <div class="ui huge primary button">Get Started <i class="right arrow icon"></i></div>
    </div>  
  </div>

  <div id="how-it-works" class="ui vertical center aligned segment">
    <div class="ui text container">
    <h1 class="ui header">How it works</h1>
    <h2 class="ui header">Step 1</h2>
    <p>We can give your company superpowers to do things that they never thought possible. Let us delight your customers and empower your needs...through pure data analytics.</p>
    <h2 class="ui header">Step 2</h2>
    <p>Yes that's right, you thought it was the stuff of dreams, but even bananas can be bioengineered.</p>
    <h2 class="ui header">Step 3</h2>
    <p>Yes that's right, you thought it was the stuff of dreams, but even bananas can be bioengineered.</p>
    <a class="ui huge button">Get Started Mofos</a>
    </div>
  </div>


{% endblock %}

app/templates/layout.html
{# TODO: Need to change the structure of this html page #}
{% extends 'base.html' %}
{% block header %}
<div class="content navbar">
  <div class="left">
    <a class="logo" href="{{ url_for('page.home') }}">EquityBuilder</a>
    <!--TODO: Fix this anchor tag-->
  </div>
  {% if current_user.is_authenticated %}
    <div class="right">
      <a class="item" href="{{ url_for('user.subscription') }}">Subscription</a>
      <a class="item" href="{{ url_for('page.faq') }}">FAQ</a>
      <a class="item" href="{{ url_for('user.account_settings') }}">Settings</a>
      <a class="btn" href="{{ url_for('user.logout') }}">Log Out</a>
    </div>
  {% else %}
    <div class="right">
      <a class="item" href="{{ url_for('page.about_the_strategy') }}">The Strategy</a>
      <a class="item" href="{{ url_for('page.faq') }}">FAQ</a>
      <a class="item login" href="{{ url_for('user.login') }}">Log In</a>
      <a class="btn" href="{{ url_for('user.signup') }}">Sign Up</a>
    </div>
  {% endif %}
</div>
{% endblock %}
{% block footer %}
{% if not current_user.is_authenticated %}
  <div class="footer">
    <div class="content">
      <a class="logo" href="{{ url_for('page.home') }}">EquityBuilder</a>
      <a class="item" href="{{ url_for('page.about') }}">About Us</a>
      <a class="item" href="{{ url_for('page.faq') }}">FAQ</a>
      <a class="item" href="mailto:support@equitybuilder.io">Contact Us</a>
    </div>
  </div>
{% endif %}
{% endblock %}